FROM openjdk:11-jdk-slim

WORKDIR /app

# Copiar el archivo JAR al contenedor
COPY target/cli-input-adapter-0.0.1-SNAPSHOT.jar /app/cli-input-adapter.jar

CMD ["java", "-jar", "cli-input-adapter.jar"]
